<?php
// rollar va dostup
return [

    /* Rector */
    'rector' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'area_view',
        'citizenship_view',
        'country_view',


        'notification_create',
        'notification_delete',
        'notification_index',
        'notification_my',

        'notification_update',
        'notification_view',

        'region_view',

        // 'user_view',

        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        // statistic
        'statistic_student-count-by-faculty',


        'job_index',
        'job_create',
        'job_update',
        'job_view',
        'job_delete',
    ],

    /* Pro rektor */
    'prorector' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',

        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'job_index',
        'job_create',
        'job_update',
        'job_view',
        'job_delete',
    ],

    /* O'quv bo'limi Admin */
    'edu_admin' => [
        "user_self",
        "user_selfget",

        "access-control_roles",

        "area_index",
        "area_view",
        "building_create",
        "building_index",
        "building_update",
        "building_view",
        "citizenship_index",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "department_index",
        "direction_create",
        "direction_index",
        "direction_update",
        "direction_view",
        "edu-form_create",
        "edu-form_index",
        "edu-form_update",
        "edu-form_view",
        "edu-plan_create",
        "edu-plan_delete",
        "edu-plan_index",
        "edu-plan_update",
        "edu-plan_view",
        "edu-semestr-subject_create",
        "edu-semestr-subject_delete",
        "edu-semestr-subject_index",
        "edu-semestr-subject_update",
        "edu-semestr-subject_view",
        "edu-semestr_create",
        "edu-semestr_index",
        "edu-semestr_update",
        "edu-semestr_view",
        "edu-type_index",
        "edu-year_create",
        "edu-year_index",
        "edu-year_update",
        "edu-year_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-semeta_index",
        "exam-student_index",
        "exam-student_update",
        "exams-type_create",
        "exams-type_index",
        "exams-type_update",
        "exams-type_view",
        "exam_ad",
        "exam_appeal-distribution",
        "exam_create",
        "exam_distribution",
        "exam_generate-passwords",
        "exam_get-passwords",
        "exam_index",
        "exam_update",
        "exam_view",
        "faculty_create",
        "faculty_index",
        "faculty_update",
        "faculty_view",
        "hostel-app_index",
        "hostel-category-type_index",
        "hostel-category_index",
        "kafedra_create",
        "kafedra_index",
        "kafedra_update",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_create",
        "para_index",
        "para_update",
        "para_view",
        "password_index",
        "password_update",
        "password_view",
        "question-type_create",
        "question-type_index",
        "question-type_update",
        "question-type_view",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_view",
        "region_index",
        "region_view",
        "room_create",
        "room_free",
        "room_index",
        "room_update",
        "room_view",
        "semestr_index",
        "semestr_view",
        "statistic_checking",
        "statistic_student-count-by-faculty",
        "student_create",
        "student_index",
        "student_update",
        "student_view",
        "subject-category_create",
        "subject-category_index",
        "subject-category_update",
        "subject-category_view",
        "subject-content_index",
        "subject-content_types",
        "subject-content_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-type_create",
        "subject-type_index",
        "subject-type_update",
        "subject-type_view",
        "subject_create",
        "subject_index",
        "subject_update",
        "subject_view",
        "teacher-access_free",
        "teacher-access_index",
        "teacher-access_view",
        "teacher-access_update",

        "time-table_create",
        // "time-table_delete",
        "time-table_index",
        "time-table_parent-null",
        // "time-table_update",
        "time-table_view",


        "time-option_create",
        "time-option_delete",
        "time-option_index",
        "time-option_update",
        "time-option_view",

        "user-access-type_index",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_status-list",
        "user_update",
        "user_view",
        "week_index",
        "week_view"
    ],

    /* O'quv bo'limi kontenthisi */
    'edu_moderator' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        // 'time-table_index',
        // 'time-table_create',
        // 'time-table_update',
        // 'time-table_view',
        // 'time-table_delete',
    ],

    /* O'quv bo'limi nazoratchi */
    'edu_editor' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        /**1 */


        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',
        /**
         * 
         */
        'languages_index',
        'teacher-access_index',
        'citizenship_index',
        'nationality_index',
        'course_index',
        'area_index',
        'region_index',
        'country_index',
        'area_view',
        'region_view',
        'country_view',

        'user-access-type_index',


        'building_index',
        'building_create',
        'building_update',
        'building_view',

        'room_index',
        'room_create',
        'room_update',
        'room_view',

        'edu-form_index',
        'edu-form_create',
        'edu-form_update',
        'edu-form_view',

        'para_index',
        'para_create',
        'para_update',
        'para_view',

        // 'exam_index',
        // 'exam_create',
        // 'exam_update',
        // 'exam_view',

        'exams-type_index',
        'exams-type_create',
        'exams-type_update',
        'exams-type_view',

        'subject-type_index',
        'subject-type_create',
        'subject-type_update',
        'subject-type_view',

        'subject-category_index',
        'subject-category_create',
        'subject-category_update',
        'subject-category_view',

        'edu-year_index',
        'edu-year_create',
        'edu-year_update',
        'edu-year_view',

        'edu-semestr_index',
        'edu-semestr_create',
        'edu-semestr_update',
        'edu-semestr_view',

        'question-type_index',
        'question-type_create',
        'question-type_update',
        'question-type_view',

        'direction_index',
        'direction_create',
        'direction_update',
        'direction_view',

        'faculty_index',
        'department_index',
        'faculty_create',
        'faculty_update',
        'faculty_view',

        'kafedra_index',
        'kafedra_create',
        'kafedra_update',
        'kafedra_view',

        'student_index',
        'student_create',
        'student_update',
        'student_view',


        // 'time-table_index',
        // 'time-table_create',
        // 'time-table_update',
        // 'time-table_view',
        // 'time-table_delete',
    ],

    /* O'quv bo'limi yordamchi */
    'edu_viewer' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////

        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',
        /**
         * 
         */
        'languages_index',
        'teacher-access_index',
        'citizenship_index',
        'nationality_index',
        'course_index',
        'area_index',
        'region_index',
        'country_index',
        'area_view',
        'region_view',
        'country_view',

        'user-access-type_index',


        'building_index',
        'building_create',
        'building_update',
        'building_view',

        'room_index',
        'room_create',
        'room_update',
        'room_view',

        'edu-form_index',
        'edu-form_create',
        'edu-form_update',
        'edu-form_view',

        'para_index',
        'para_create',
        'para_update',
        'para_view',

        // 'exam_index',
        // 'exam_create',
        // 'exam_update',
        // 'exam_view',

        'exams-type_index',
        'exams-type_create',
        'exams-type_update',
        'exams-type_view',

        'subject-type_index',
        'subject-type_create',
        'subject-type_update',
        'subject-type_view',

        'subject-category_index',
        'subject-category_create',
        'subject-category_update',
        'subject-category_view',

        'edu-year_index',
        'edu-year_create',
        'edu-year_update',
        'edu-year_view',

        'edu-semestr_index',
        'edu-semestr_create',
        'edu-semestr_update',
        'edu-semestr_view',

        'question-type_index',
        'question-type_create',
        'question-type_update',
        'question-type_view',

        'direction_index',
        'direction_create',
        'direction_update',
        'direction_view',

        'faculty_index',
        'department_index',
        'faculty_create',
        'faculty_update',
        'faculty_view',

        'kafedra_index',
        'kafedra_create',
        'kafedra_update',
        'kafedra_view',

        'student_index',
        'student_create',
        'student_update',
        'student_view',

    ],

    /* Talim sifati */
    'edu_quality' => [
        "access-control_roles",
        "area_index",
        "area_view",
        // "building_create",
        "building_index",
        // "building_update",
        "building_view",
        "citizenship_index",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "faculty_index",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "password_index",
        "password_view",
        "region_index",
        "region_view",
        "room_index",
        "room_view",
        "subject-category_index",
        "subject-category_view",
        "subject-content-mark_index",
        "subject-content-mark_view",
        "subject-content_index",
        "subject-content_types",
        "subject-content_view",
        "subject-sillabus_index",
        "subject-sillabus_view",
        "subject-topic-reference_index",
        "subject-topic-reference_view",
        "subject-topic_index",
        "subject-topic_view",
        "subject-type_index",
        "subject-type_view",
        "subject_index",
        "subject_view",
        "teacher-access_index",
        "teacher-access_view",
        "teacher-content_create",
        "teacher-content_delete",
        "teacher-content_index",
        "teacher-content_update",
        "teacher-content_view",
        "user-access-type_index",
        "user_index",

        "kpi-category_index",
        "kpi-category_view",
        "kpi-data_view",
        "kpi-data_index",
        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "user_view",
        "week_index",
        "week_view"
    ],


    /* Dekan huquqlari */
    'dean' => [
        "user_self",
        "user_selfget",

        "access-control_permissions",
        "access-control_roles",
        "area_index",
        "area_view",
        "building_index",
        "building_view",
        "citizenship_index",
        "citizenship_view",
        "country_index",
        "country_view",
        "course_index",
        "department_index",
        "department_types",
        "direction_create",
        "direction_delete",
        "direction_index",
        "direction_update",
        "direction_view",
        "edu-form_index",
        "edu-plan_create",
        "edu-plan_delete",
        "edu-plan_index",
        "edu-plan_update",
        "edu-plan_view",
        "edu-semestr-subject_create",
        "edu-semestr-subject_delete",
        "edu-semestr-subject_index",
        "edu-semestr-subject_update",
        "edu-semestr-subject_view",
        "edu-semestr_create",
        "edu-semestr_delete",
        "edu-semestr_index",
        "edu-semestr_update",
        "edu-semestr_view",
        "edu-type_index",
        "edu-year_index",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exams-type_index",
        // "exam_create",
        // "exam_delete",
        // "exam_index",
        // "exam_update",
        // "exam_view",
        "faculty_index",
        "faculty_view",
        "kafedra_create",
        "kafedra_delete",
        "kafedra_index",
        "kafedra_update",
        "kafedra_user-access",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_create",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_index",
        "para_view",

        "password_index",
        "password_update",

        "question_index",
        "question_status-update",
        "question_update",
        "question_view",

        'question_status-list',

        "region_index",
        "region_view",
        "room_free",
        "room_index",
        "room_view",

        "semestr_index",
        "semestr_update",
        "semestr_view",

        "student_create",
        "student_delete",
        "student_index",
        "student_update",
        "student_view",
        "student-category_index",
        "student-category_view",

        "student_time-option-not",

        "subject-category_index",
        "subject-category_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-type_index",
        "subject-type_view",
        "subject_index",
        "subject_view",

        "subject-content_index",
        "subject-topic_index",
        "subject-content_view",
        "subject-topic_view",

        "teacher-access_free",
        "teacher-access_index",
        "teacher-access_view",

        // "time-table_create",
        // "time-table_delete",
        "time-table_index",
        "time-table_parent-null",
        // "time-table_update",
        "time-table_view",

        "user-access-type_index",
        "user-access_create",
        "user-access_delete",
        "user-access_index",
        "user-access_update",
        "user-access_view",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_status-list",
        "user_update",
        "user_view",

        "week_index",
        "week_view",

        'statistic_checking',



    ],
    /* Dekan huquqlari */

    /* Zam Dekan huquqlari */
    'dean_deputy' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'user_logout',
        'user_me',
        'notification_approved',
        'notification_status-list',


        'user_status-list',
        'user_index',
        'user_create',
        'user_update',
        'user_view',
        'user_delete',

        'user-access_index',
        'user-access_create',
        'user-access_update',
        'user-access_view',
        'user-access_delete',

        'notification_create',
        'notification_index',
        'notification_my',

        'region_index',
        'region_view',

        'nationality_index',
        'nationality_view',

        'languages_index',
        'languages_view',

        'country_index',
        'country_view',

        'area_index',
        'area_view',

    ],

    /* Kafedra mudiri */
    'mudir' => [

        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        // "time-table_create",
        // "time-table_update",
        // "time-table_delete",

        "building_index",
        "room_index",
        "room_free",
        "teacher-access_free",
        "para_index",
        "week_index",
        "edu-plan_index",
        "edu-semestr_index",
        "edu-semestr-subject_index",


        "academic-degree_index",
        "academic-degree_view",
        "access-control_permissions",
        "access-control_roles",
        "area_index",
        "area_view",
        "citizenship_view",
        "country_index",
        "country_view",
        "course_index",
        "course_view",
        "degree-info_index",
        "degree-info_view",
        "degree_index",
        "degree_view",
        "department_index",
        "diploma-type_index",
        "diploma-type_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-appeal-semeta_create",
        "exam-appeal-semeta_index",
        "exam-appeal-semeta_view",
        "exam-checking_index",
        "exam-checking_update",
        "exam-checking_view",
        "exam-question_index",
        "exam-question_view",
        "exam-semeta_create",
        "exam-semeta_index",
        "exam-semeta_view",
        "exams-type_index",
        "exams-type_view",
        "exam_index",
        "exam_view",
        "faculty_index",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "partiya_index",
        "partiya_view",
        "password_index",
        "password_update",
        "password_view",
        "question-type_index",
        "question-type_view",
        "question_create",
        "question_delete",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_update",
        "question_view",
        "region_index",
        "region_view",
        "semestr_index",
        "statistic_checking",
        "subject-category_index",
        "subject-category_view",
        "subject-sillabus_create",
        "subject-sillabus_delete",
        "subject-sillabus_index",
        "subject-sillabus_update",
        "subject-sillabus_view",
        "subject-topic_create",
        "subject-topic_delete",
        "subject-topic_index",
        "subject-topic_update",
        "subject-topic_view",
        "subject-type_index",
        "subject-type_view",
        "subject_create",
        "subject_index",
        "subject_update",
        "subject_view",
        "teacher-access_index",
        "teacher-access_update",
        "user-access-type_index",
        "user-access_create",
        "user-access_delete",
        "user-access_index",
        "user-access_update",
        "user-access_view",
        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "user_update",
        "user_view",

    ],


    /* tutor tarbiyachi huquqlari */
    'tutor' => [


        "area_index",
        "citizenship_index",
        "country_index",
        "course_index",
        "department_index",
        "department_types",
        "direction_index",
        "edu-form_index",
        "edu-plan_index",
        "edu-type_index",
        "edu-year_index",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "faculty_index",
        "faculty_view",
        "kafedra_index",
        "kafedra_view",
        "languages_index",
        "nationality_index",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "para_index",
        "para_view",
        "password_index",
        "password_update",
        "region_index",
        "student-category_index",
        "student-category_view",
        "student_create",
        "student_delete",
        "student_import",
        "student_index",
        "student_update",
        "student_view",

        "student_time-option-not",

        "subject_index",
        "subject_view",

        "time-option_index",
        "time-option_view",
        "time-table_index",
        "time-table_parent-null",
        // "time-table_update",
        "time-table_view",

        "user_logout",
        "user_me",
        "user_self",
        "user_selfget",
        "user_status-list",
        "week_index",
        "week_view",
        'room_index',
        'room_view',
        'building_index',
        'building_view',
        'subject-type_index',
        'student-time-table_index',
        'student-time-option_index',

    ],


    /* Bo'lim boshlig'i */
    'dep_lead' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'notification_approved',
        'notification_status-list',

        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'user_logout',
        'user_me',



        'department_update',
        'department_view',



    ],


    /* Kadr */
    'hr' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',


        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",


        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        "region_index",
        "region_view",


        'department_index',
        'department_types',
        'department_view',
        // 'department_create',
        // 'department_update',
        // 'department_delete',

        'kafedra_index',
        'kafedra_view',
        // 'kafedra_create',
        // 'kafedra_update',
        // 'kafedra_delete',

        'faculty_index',
        'faculty_view',
        // 'faculty_create',
        // 'faculty_update',
        // 'faculty_delete',

        'user-access_index',
        'user-access_view',
        'user-access_create',
        'user-access_update',
        'user-access_delete',

        'table-store_index',
        'table-store_view',
        'table-store_create',
        'table-store_update',
        'table-store_delete',

        'work-rate_index',
        'work-rate_view',
        'work-rate_create',
        'work-rate_update',
        'work-rate_delete',

        'job-title_index',
        'job-title_view',
        'job-title_create',
        'job-title_update',
        'job-title_delete',

        'vocation_index',
        'vocation_view',
        'vocation_create',
        'vocation_update',
        'vocation_delete',

        'holiday_index',
        'holiday_view',
        'holiday_create',
        'holiday_update',
        'holiday_delete',

        "user-access-type_index",

        "user_create",
        "user_delete",
        "user_index",
        "user_logout",
        "user_me",
        "user_update",
        "user_view",

        "user_status-list",


    ],

    /* Kadr yordamchi */
    'hr_viewer' => [
        "user_self",
        "user_selfget",

        'password_index',
        'password_update',
        'notification_approved',
        'notification_status-list',
        'access-control_roles',
        'access-control_permissions',
        'enum_education-degrees',
        'enum_education-types',
        'enum_educations',
        'enum_family-statuses',
        'enum_genders',
        'enum_rates',
        'enum_topic-types',
        'enum_yesno',
        ////


        'department_index',

        'department_view',
    ],

    /* Teacher */
    'teacher' => [
        "user_self",
        "user_selfget",

        "course_index",
        "exam-appeal_index",
        "exam-appeal_update",
        "exam-appeal_view",
        "exam-checking_appeal",
        "exam-checking_index",
        "exam-checking_update",
        "exam-checking_view",
        "exam-semeta_index",
        "exam-student_index",
        "exam-student_update",
        "exam-student_view",
        "exam-teacher-check_index",
        "exam-teacher-check_view",
        "exam_index",
        "exam_view",
        "kpi-category_extra",
        "kpi-category_index",
        // "kpi-data_create",
        // "kpi-data_delete",
        "kpi-data_index",
        // "kpi-data_update",
        "kpi-data_view",
        "lang-certificate-type_index",
        "lang-certificate-type_view",
        "lang-certificate_index",
        "lang-certificate_view",
        "languages_index",
        "notification_approved",
        "notification_index",
        "password_update",
        "question-type_index",
        "question_create",
        "question_delete",
        "question_index",
        "question_status-list",
        "question_status-update",
        "question_update",
        "question_view",
        "semestr_index",
        "subject-category_index",
        "subject-content_index",
        "subject-content_types",

        // "subject-content_create",

        "subject-content_update",
        // "subject-content_delete",
        "subject-content_view",
        "subject-sillabus_index",
        "subject-topic-reference_create",
        "subject-topic-reference_delete",
        "subject-topic-reference_index",
        "subject-topic-reference_update",
        "subject-topic-reference_view",
        "subject-topic_index",
        "subject-topic_view",
        "subject_index",
        "user_logout",
        "user_me",

        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        "week_index",
        "para_index",
    ],

    /* Student  */
    'student' => [
        "user_self",
        "user_selfget",
        "para_index",
        'student_me',

        "access-control_permissions",
        "access-control_roles",
        "area_view",
        "building_view",
        "country_view",
        "course_index",
        "course_view",
        "direction_view",
        "edu-plan_view",
        "edu-semestr-subject-category-time_view",
        "edu-semestr-subject_index",
        "edu-semestr-subject_view",
        "edu-semestr_index",
        "edu-semestr_view",
        "edu-type_view",
        "edu-year_view",
        "enum_education-degrees",
        "enum_education-types",
        "enum_educations",
        "enum_family-statuses",
        "enum_genders",
        "enum_rates",
        "enum_topic-types",
        "enum_yesno",
        "exam-student-answer_create",
        "exam-student-answer_get-question",
        "exam-student-answer_index",
        "exam-student-answer_update",
        "exam-student-answer_view",
        "exam-student_index",
        "exam-student_update",
        "exam-student_view",
        "exams-type_view",
        "exam_index",
        "exam_view",

        'exam-appeal_view',
        // "exam-appeal_create",
        // 'exam-appeal_delete',
        // 'exam-appeal_update',

        "faculty_view",
        "kafedra_view",
        "languages_view",
        "notification_approved",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_view",
        "para_view",
        "password_index",

        "password_update",
        "region_view",
        "room_view",
        "semestr_index",
        "semestr_view",
        "student-exam_create",
        "student-exam_delete",
        "student-exam_index",
        "student-exam_update",
        "student-exam_view",



        "subject-category_index",
        "subject-category_view",
        "subject-content_index",
        "subject-topic_index",
        "subject-type_index",
        "subject-type_view",
        "subject_view",
        "time-table_index",
        "time-table_parent-null",
        "time-table_view",
        "user_logout",
        "user_me",
        "week_index",
        "week_view",

        'survey-answer_create',
        'survey-answer_update',
        'survey-question_index',

        'election_index',
        'election-vote_create',
        'election-vote_update',

        'hostel-app_index',
        'hostel-app_create',
        'hostel-app_update',
        'hostel-app_view',
        'hostel-app_delete',

        'hostel-doc_index',
        'hostel-doc_create',
        'hostel-doc_update',
        'hostel-doc_view',
        'hostel-doc_delete',

        'student-subject-selection_index',
        'student-subject-selection_create',
        'student-subject-selection_update',
        'student-subject-selection_view',
        'student-subject-selection_delete',

        'hostel-category-type_index',
        'hostel-category_index',

        "time-option_index",
        "time-option_view",

        "student-time-option_create",
        // "student-time-option_delete",
        "student-time-option_index",
        "student-time-option_view",

        "student-time-table_create",
        "student-time-table_delete",
        "student-time-table_index",
        // "student-time-table_update",
        "student-time-table_view",


    ],

    'contenter' => [
        "user_self",
        "user_selfget",

        'access-control_roles',
        'area_index',
        'area_view',
        'region_index',
        "user-access-type_index",
        "teacher-access_index",
        'kafedra_index',
        'kafedra_user-access',
        'kafedra_view',
        // 'subject-content-mark_create',
        // 'subject-content-mark_delete',
        'subject-content-mark_index',
        // 'subject-content-mark_update',
        'subject-content-mark_view',
        'subject-content_index',
        'subject-content_order',
        'subject-content_trash',
        'subject-content_trash-delete',
        'subject-content_types',
        // 'subject-content_update',
        'subject-content_view',
        'subject-topic_index',
        'subject-topic_view',
        'subject-type_index',
        'subject-type_view',
        'subject_index',
        'subject_view',
        'user_index',
        'user_logout',
        'user_me',
        'user_status-list',
        'user_view',
        'teacher-content_index',
        'teacher-content_view'

    ],

    'time_table_plus' => [

        // // "time-table_create",
        // "time-table_delete",
        // // "time-table_index",
        // "time-table_parent-null",
        // // "time-table_update",
        // "time-table_view",

    ],

    'content_assign' => [

        "user_self",
        "user_selfget",
        "user_logout",
        "user_me",
        'user_index',
        'teacher-content_index',
        'teacher-content_view',
        'teacher-content_update',
        'teacher-content_create',
        'teacher-content_delete',
        'subject_index',
        'subject_view',

    ],

    'kpi_check' => [
        // "access-control_roles",
        // "kpi-category_extra",
        // "kpi-category_index",
        // "kpi-category_update",
        // "kpi-category_view",

        // "kpi-data_index",
        // // "kpi-data_update",
        // "kpi-data_view",

        // "kpi-mark_create",
        // "kpi-mark_delete",
        // "kpi-mark_index",
        // "kpi-mark_update",
        // "kpi-mark_view",
        // "kpi-store_create",
        // "kpi-store_delete",
        // "kpi-store_index",
        // "kpi-store_update",
        // "kpi-store_view",
        // "lang-certificate-type_index",
        // "lang-certificate-type_update",
        // "lang-certificate-type_view",
        // "languages_index",
        // "notification_index",
        // "notification_my",
        // "region_index",
        // "subject-category_index",
        // "kafedra_index",
        // "user_index",
        // "user_logout",
        // "user_me",
        // "user_self",
        // "user_selfget",
        // "user_status-list",
        // "user_view"
    ],

    'student_time_table_plus' => [
        // "student-time-table_create",
        // "student-time-table_delete",
        // "student-time-table_index",
        // "student-time-table_update",
        // "student-time-table_view",
    ],

    'kpi_plus' => [

        // 'kpi-category_extra',
        // 'kpi-category_index',
        // 'kpi-category_view',
        // 'kpi-data_index',
        // 'kpi-data_update',
        // 'kpi-data_create',
        // 'kpi-data_view',
    ],

    'hostel' => [

        "user_self",
        "user_selfget",
        "course_index",
        "faculty_index",
        "hostel-app_update",
        "hostel-app_index",
        "hostel-app_view",
        "hostel-category-type_create",
        "hostel-category-type_delete",
        "hostel-category-type_index",
        "hostel-category-type_update",
        "hostel-category-type_view",
        "hostel-category_create",
        "hostel-category_delete",
        "hostel-category_index",
        "hostel-category_update",
        "hostel-category_view",
        "hostel-doc_check",
        "hostel-doc_index",
        "hostel-doc_not",
        "hostel-doc_view",
        "notification_approved",
        "notification_create",
        "notification_delete",
        "notification_index",
        "notification_my",
        "notification_status-list",
        "notification_update",
        "notification_view",
        "student_view",
        "system_language",
        "user_logout",
        "user_me",

    ],

    'content_plus' => [
        // "subject-content_create",
        // "subject-content_update",
        // "subject-content_delete",
        // "subject-content_view",
    ]
];
